from snakemake.utils import min_version

min_version("9.12.0")


# load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"


inputflags:
    access.sequential,


# Allow users to fix the underlying OS via singularity.
container: "docker://continuumio/miniconda3"


# load helpers first
# -----------------------------------------------------
include: "rules/common.smk"


# config-driven pathvars for candidate final BAM stages
# -----------------------------------------------------
pathvars:
    results_bqsr=get_results_bqsr(),
    results_consensus=get_results_consensus(),
    results_trimmed=get_results_trimmed(),
    results_dedup=get_results_dedup(),
    results_mapped_bwa=get_results_mapped_bwa(),
    results_mapped_vg=get_results_mapped_vg(),


# load rules
# -----------------------------------------------------
include: "rules/utils.smk"
include: "rules/ref.smk"
include: "rules/trimming.smk"
include: "rules/mapping.smk"
include: "rules/primers.smk"


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


rule all:
    input:
        expand("<results>/{sample}.bam", sample=list(samples.index)),
    default_target: True
