samples: "config-pangenome-on/samples.tsv"
units: "config-pangenome-on/units.tsv"

remove_duplicates:
  activate: false

calc_consensus_reads:
  activate: false

ref:
  species: "homo_sapiens"
  release: 111
  build: "GRCh38"
  pangenome:
    activate: true
    source: "hprc"
    version: "v1.1"

primers:
  trimming:
    primers_fa1: ""
    primers_fa2: ""
    tsv: "config-pangenome-on/primers.tsv"
    library_length: 0

params:
  fastp: ""
  picard:
    MarkDuplicates: "--VALIDATION_STRINGENCY LENIENT"
  gatk:
    BaseRecalibrator: ""
    applyBQSR: ""
