samples: "config/samples.tsv"
units: "config/units.tsv"

kmc_threads: 8

ref:
  species: "homo_sapiens"
  release: 111
  build: "GRCh38"
  pangenome:
    activate: false
    source: "hprc"
    version: "freeze1"

primers:
  trimming:
    activate: false
    primers_fa1: ""
    primers_fa2: ""
    tsv: "config/primers.tsv"
    library_length: 0

params:
  fastp: ""
