samples: "config/samples.tsv"
units: "config/units.tsv"

kmc_threads: 8

ref:
  species: "homo_sapiens"
  release: 111
  build: "GRCh38"
  pangenome:
    activate: false
    source: "hprc"
    version: "freeze1"

primers:
  trimming:
    tsv: "config/primers.tsv"

params:
  fastp: ""
