$schema: "https://json-schema.org/draft/2020-12/schema"

description: read-alignment-pangenome workflow configuration (pangenome download + trimming + vg giraffe mapping + postprocessing + CRAM + QC)

type: object

properties:
  samples:
    type: string

  units:
    type: string

  kmc_threads:
    type: integer
    minimum: 1
    maximum: 128
    default: 8

  ref:
    type: object
    properties:
      species:
        type: string
      release:
        type: integer
      build:
        type: string
      pangenome:
        type: object
        properties:
          activate:
            type: boolean
          source:
            type: string
          version:
            type: string
        required:
          - activate
          - source
          - version
    required:
      - species
      - release
      - build
      - pangenome

  primers:
    type: object
    properties:
      trimming:
        type: object
        properties:
          primers_fa1:
            type: string
          primers_fa2:
            type: string
          tsv:
            type: string
          library_length:
            type: integer
        required:
          - tsv
    required:
      - trimming

  params:
    type: object
    properties:
      fastp:
        type: string
    required:
      - fastp

required:
  - samples
  - units
  - ref
  - primers
  - params
