name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        case:
          - name: default
            args: >-
              --configfile .test/config-default/config.yaml
              --show-failed-logs
              --cores 2
              --conda-cleanup-pkgs cache
              --all-temp
              --dryrun
            cleanup: false
          - name: primers off
            args: >-
              --configfile .test/config-primers-off/config.yaml
              --show-failed-logs
              --cores 2
              --conda-cleanup-pkgs cache
              --all-temp
              --dryrun
            cleanup: false
          - name: pangenome on
            args: >-
              --configfile .test/config-pangenome-on/config.yaml
              --show-failed-logs
              --cores 2
              --conda-cleanup-pkgs cache
              --all-temp
              --dryrun
            cleanup: false
          - name: sra
            args: >-
              --configfile .test/config-sra/config.yaml
              --show-failed-logs
              --cores 2
              --conda-cleanup-pkgs cache
              --all-temp
              --dryrun
            cleanup: false
    name: test ${{ matrix.case.name }}

    steps:
      - name: update apt
        run: sudo apt-get update

      - name: Free Disk Space (Ubuntu)
        if: ${{ matrix.case.cleanup }}
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: true

      - uses: actions/checkout@v4

      - name: run workflow
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: .test
          snakefile: workflow/Snakefile
          args: >
            --sdm conda --resources mem_mb=16000 ${{ matrix.case.args }}
          show-disk-usage-on-error: true
